#!/usr/bin/env python3
"""Download every pet in the wardrobe once and save it in the repo, so the site never fetches pets live.

Usage: python3 bake_pets.py          (skips pets that are already saved)
       python3 bake_pets.py --force  (re-downloads everything)
Output: assets/pets/<id>.js, each defining window.MAPLE_PETS[<id>] with the frames the game uses.
The pet list is the shared favorites in assets.js plus every month's pets in themes/*.js.
"""
import concurrent.futures as cf
import glob
import json
import os
import sys

from build_assets import API, REGION, VERSION, fetch_json

OUT = "assets/pets"
# Animations the game actually plays; the rest (food, dung, cry, ...) are skipped to keep files small.
USED_ANIMS = {"stand0", "stand1", "move", "jump", "sit", "sleep", "rest0", "love", "dancing", "chat", "hungry", "play"}


def read_js_object(path):
    src = open(path).read()
    return json.loads(src[src.index("= ") + 2:].rstrip().rstrip(";"))


def pet_ids():
    ids = []
    assets = read_js_object("assets.js")
    ids.append(assets["pet"]["id"])
    ids += [p["id"] for p in assets["wardrobe"]["pets"] if isinstance(p["id"], int)]
    for path in sorted(glob.glob("themes/*.js")):
        src = open(path).read()
        theme = json.loads(src[src.index("] = ") + 4:].rstrip().rstrip(";"))
        ids += [p["id"] for p in theme.get("pets", [])]
    return list(dict.fromkeys(ids))


def bake(pet_id, force):
    path = f"{OUT}/{pet_id}.js"
    if os.path.exists(path) and not force:
        return pet_id, "kept"
    d = fetch_json(f"{API}/{REGION}/{VERSION}/pet/{pet_id}")
    anims = {}
    for name, books in d["frameBooks"].items():
        if name not in USED_ANIMS:
            continue
        book = books[0] if isinstance(books, list) and books else books
        frames = [f for f in ((book or {}).get("frames") or []) if f.get("image") and f.get("origin")]
        if frames:
            anims[name] = [{"src": "data:image/png;base64," + f["image"], "ox": f["origin"]["x"],
                            "oy": f["origin"]["y"], "delay": f.get("delay") or 180} for f in frames]
    if "stand0" not in anims or "move" not in anims:
        return pet_id, "skipped (missing standing or walking animation)"
    data = {"id": pet_id, "name": d["description"]["name"],
            "desc": d["description"].get("description", ""), "anims": anims}
    with open(path, "w") as f:
        f.write(f"// Generated by bake_pets.py from maplestory.io (GMS v{VERSION}). Do not edit.\n")
        f.write("(window.MAPLE_PETS = window.MAPLE_PETS || {})[%d] = " % pet_id)
        json.dump(data, f, separators=(",", ":"))
        f.write(";\n")
    return pet_id, f"saved ({os.path.getsize(path) // 1024} KB)"


def main():
    os.makedirs(OUT, exist_ok=True)
    force = "--force" in sys.argv
    ids = pet_ids()
    print(f"{len(ids)} pets")
    failed = []
    with cf.ThreadPoolExecutor(3) as ex:
        for pet_id, result in ex.map(lambda i: safe_bake(i, force), ids):
            print(f"  {pet_id}: {result}")
            if result.startswith("FAILED"):
                failed.append(pet_id)
    if failed:
        print(f"{len(failed)} failed; run again to retry them: {failed}")


def safe_bake(pet_id, force):
    try:
        return bake(pet_id, force)
    except Exception as e:
        return pet_id, f"FAILED ({e})"


if __name__ == "__main__":
    main()
