#!/usr/bin/env python3
"""Build one monthly map theme from its spec.

Usage: python3 build_theme.py themes/oct.json [--skip-validate]
Output: themes/<key>.js (defines window.MAPLE_THEMES[key]) and images under assets/themes/<key>/.

A spec looks like this (see themes/oct.json for a full example):
{
  "key": "oct", "month": 10, "name": "Halloween", "accent": "#ff9a3c",
  "sprites": { "moon": "Map/Back/HalloweenBack.img/back/11",
               "fish": {"path": "Mob/2230109.img/move", "version": "250"} },
  "scene": { ... how the sprites are arranged; read by index.html ... },
  "wardrobe": { "hat": [[1001002, "Witch Hat"], ...], "outfit": [...], "cape": [...],
                "shoes": [...], "face": [...], "weapon": [...] },
  "pets": [5000036, ...]
}
Every wardrobe item is checked to actually show up on the character before it is kept.
"""
import concurrent.futures as cf
import io
import json
import os
import sys
import time

from PIL import Image

from build_assets import API, REGION, VERSION, fetch, fetch_json, save_png, wz_sprite

BASE_BODY = [12000, 21000, 31000]
SLOT_TABS = ["hat", "outfit", "cape", "shoes", "face", "weapon"]


def slot_for(tab, item_id):
    if tab == "face":
        return "faceAcc" if item_id // 10000 == 101 else "eyeAcc"
    return tab


def fetch_retry(url, tries=5):
    for attempt in range(1, tries + 1):
        try:
            return fetch(url)
        except Exception:
            if attempt == tries:
                raise
            time.sleep(0.8 * attempt)


def render_pixels(items, action):
    png, _ = fetch_retry(f"{API}/{REGION}/{VERSION}/Character/feetCenter/2000/{','.join(map(str, items))}/{action}/0")
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    return img.size, img.tobytes()


def validate_items(entries):
    """Keep items that visibly change the standing and walking character."""
    base = {a: render_pixels(BASE_BODY, a) for a in ("stand1", "walk1")}

    def ok(entry):
        item_id = entry[0]
        try:
            return all(render_pixels(BASE_BODY + [item_id], a) != base[a] for a in ("stand1", "walk1"))
        except Exception:
            return False

    with cf.ThreadPoolExecutor(3) as ex:
        results = list(ex.map(ok, entries))
    return [e for e, good in zip(entries, results) if good], [e for e, good in zip(entries, results) if not good]


def build(spec_path, validate=True):
    spec = json.load(open(spec_path))
    key = spec["key"]
    out_dir = f"assets/themes/{key}"
    os.makedirs(out_dir, exist_ok=True)

    sprites = {}
    for name, src in spec["sprites"].items():
        path, version = (src["path"], src.get("version", VERSION)) if isinstance(src, dict) else (src, VERSION)
        sprites[name] = wz_sprite(path, f"{out_dir}/{name}", version)
        print(f"  sprite {name}: {len(sprites[name])} frame(s)")

    wardrobe = {}
    for tab in SLOT_TABS:
        entries = [list(e) for e in spec.get("wardrobe", {}).get(tab, [])]
        if validate and entries:
            entries, dropped = validate_items(entries)
            for d in dropped:
                print(f"  dropped {tab} {d[0]} {d[1]}: doesn't render on the character")
        wardrobe[tab] = []
        for item_id, name in entries:
            try:
                icon = save_png(fetch_retry(f"{API}/{REGION}/{VERSION}/item/{item_id}/iconRaw")[0], f"{out_dir}/icon_{item_id}.png")
            except Exception as e:
                print(f"  dropped {tab} {item_id} {name}: no icon ({e})")
                continue
            wardrobe[tab].append({"id": item_id, "name": name, "slot": slot_for(tab, item_id), "icon": icon})
        print(f"  wardrobe {tab}: {len(wardrobe[tab])}")

    pets = []
    for pet_id in spec.get("pets", []):
        try:
            d = fetch_json(f"{API}/{REGION}/{VERSION}/pet/{pet_id}")
            if "stand0" not in d["frameBooks"] or "move" not in d["frameBooks"]:
                raise ValueError("missing stand0/move")
            icon = save_png(fetch_retry(f"{API}/{REGION}/{VERSION}/item/{pet_id}/iconRaw")[0], f"{out_dir}/icon_{pet_id}.png")
            pets.append({"id": pet_id, "name": d["description"]["name"],
                         "desc": d["description"].get("description", ""), "icon": icon})
        except Exception as e:
            print(f"  dropped pet {pet_id}: {e}")
    print(f"  pets: {len(pets)}")

    theme = {k: spec[k] for k in ("key", "month", "name", "accent") if k in spec}
    theme.update({"sprites": sprites, "scene": spec["scene"], "wardrobe": wardrobe, "pets": pets})
    os.makedirs("themes", exist_ok=True)
    with open(f"themes/{key}.js", "w") as f:
        f.write(f"// Generated by build_theme.py from themes/{key}.json. Do not edit.\n")
        f.write("(window.MAPLE_THEMES = window.MAPLE_THEMES || {})[%s] = " % json.dumps(key))
        json.dump(theme, f, separators=(",", ":"))
        f.write(";\n")
    print(f"wrote themes/{key}.js")


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        sys.exit(__doc__)
    for spec_path in args:
        print(spec_path)
        build(spec_path, validate="--skip-validate" not in sys.argv)
