#!/usr/bin/env python3
"""Download sprites from the community maplestory.io API and pack them into assets.js.

Run once: python3 build_assets.py
Output: assets.js, which defines window.ASSETS so index.html works when opened directly from disk.
"""
import base64
import io
import json
import re
import urllib.parse
import urllib.request

from PIL import Image

REGION, VERSION = "GMS", "270"
API = "https://maplestory.io/api"
UA = {"User-Agent": "curl/8.7.1"}

PET_ID = 5000144  # Adriano, "a surly pirate otter of few words"
CHAIR_ID = 3015787  # Rabbit Lamp Chair
CHAIR_WZ = f"Item/Install/030157.img/0{CHAIR_ID}"

SKIN = 2000
OUTFIT = [
    12000,    # head
    21000,    # face
    31000,    # hair
    1002738,  # Bunny Earmuffs
    1052926,  # Cottontail Rabbit Dress
    1073062,  # Cottontail Rabbit Shoes
]
CHAR_ACTIONS = {"stand1": 700, "walk1": 180, "jump": 200, "sit": 1000}


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=90) as r:
        return r.read(), r.headers.get("Content-Type", "")


def fetch_json(url):
    return json.loads(fetch(url)[0])


def data_uri(png_bytes):
    return "data:image/png;base64," + base64.b64encode(png_bytes).decode()


def pixels(png_bytes):
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    return img.size, img.tobytes()


def wz(path):
    return fetch_json(f"{API}/wz/{REGION}/{VERSION}/{urllib.parse.quote(path)}")


def build_pet():
    d = fetch_json(f"{API}/{REGION}/{VERSION}/pet/{PET_ID}")
    anims = {}
    for name, books in d["frameBooks"].items():
        book = books[0] if isinstance(books, list) and books else books
        frames = [f for f in ((book or {}).get("frames") or []) if f.get("image") and f.get("origin")]
        if not frames:
            continue
        anims[name] = [
            {
                "src": "data:image/png;base64," + f["image"],
                "ox": f["origin"]["x"],
                "oy": f["origin"]["y"],
                "delay": f.get("delay") or 180,
            }
            for f in frames
        ]
    print(f"pet: {len(anims)} animations")
    return {"id": PET_ID, "name": d["description"]["name"],
            "desc": d["description"]["description"], "anims": anims}


def build_chair():
    info = wz(f"{CHAIR_WZ}/info/bodyRelMove")["value"]
    root = f"{CHAIR_WZ}/info/customChair/randomChairInfo"
    variants = []
    for v in sorted(wz(root)["children"], key=int):
        eff = f"{root}/{v}/effect"
        frame_ids = sorted((c for c in wz(eff)["children"] if c.isdigit()), key=int)
        frames = []
        for fid in frame_ids:
            node = wz(f"{eff}/{fid}")
            kids = node.get("children") or []
            origin = wz(f"{eff}/{fid}/origin")["value"]
            delay = wz(f"{eff}/{fid}/delay")["value"] if "delay" in kids else 100
            img_path = wz(f"{eff}/{fid}/_outlink")["value"] if "_outlink" in kids else f"{eff}/{fid}"
            png, _ = fetch(f"{API}/wz/img/{REGION}/{VERSION}/{urllib.parse.quote(img_path)}")
            frames.append({"src": data_uri(png), "ox": origin["x"], "oy": origin["y"], "delay": delay})
        variants.append(frames)
        print(f"chair variant {v}: {len(frames)} frames")
    name = fetch_json(f"{API}/{REGION}/{VERSION}/item/{CHAIR_ID}")["description"]
    return {"id": CHAIR_ID, "name": name["name"], "desc": re.sub(r"#c?", "", name["description"]),
            "seat": {"x": info["x"], "y": info["y"]}, "variants": variants}


def build_character():
    items = ",".join(str(i) for i in OUTFIT)
    anims = {}
    for action, delay in CHAR_ACTIONS.items():
        frames = []
        for frame in range(12):
            url = f"{API}/{REGION}/{VERSION}/Character/feetCenter/{SKIN}/{items}/{action}/{frame}"
            try:
                png, ctype = fetch(url)
            except Exception:
                break
            if "image" not in ctype:
                break
            frames.append({"_raw": png, "src": data_uri(png), "delay": delay})
        # The API wraps frame indexes past the end, so keep the shortest repeating cycle.
        # PNG metadata differs per request, so compare decoded pixels.
        raws = [pixels(f["_raw"]) for f in frames]
        period = next(p for p in range(1, len(raws) + 1)
                      if all(raws[i] == raws[i % p] for i in range(len(raws))))
        frames = frames[:period]
        for f in frames:
            del f["_raw"]
        anims[action] = frames
        print(f"character {action}: {len(frames)} frames")
    return {"skin": SKIN, "items": OUTFIT, "anims": anims}


def main():
    assets = {"pet": build_pet(), "chair": build_chair(), "character": build_character()}
    with open("assets.js", "w") as f:
        f.write("// Generated by build_assets.py from maplestory.io (GMS v%s). Do not edit.\n" % VERSION)
        f.write("window.ASSETS = ")
        json.dump(assets, f, separators=(",", ":"))
        f.write(";\n")
    print("wrote assets.js")


if __name__ == "__main__":
    main()
